# Generated by Django 6.0.4 on 2026-04-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Member', 'Member')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Klaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maskapai', models.CharField(max_length=100)),
                ('bandara_asal', models.CharField(max_length=10)),
                ('bandara_tujuan', models.CharField(max_length=10)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=20)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=10)),
                ('timestamp_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'unique_together': {('flight_number', 'tanggal_penerbangan', 'nomor_tiket')},
            },
        ),
    ]
